### ISSUE TITLE
'*Exception|Handler' is not a valid class or namespace pattern

### ISSUE THREAD

**Issue by szepeviktor** [smortexa/laravel-arkitect#19]
> '*Exception|Handler' is not a valid class or namespace pattern. Regex are not allowed, only * and ? wildcard.

Hello! There is a 🐞 

https://github.com/phparkitect/arkitect/search?q=HaveNameMatching

https://github.com/smortexa/laravel-arkitect/blob/a36b1bc6da1360b460bb28d45e4c0249975b7810/src/Rules/Naming/ExceptionsNaming.php#L24

The file: `app/Exceptions/Handler.php`

What do you think?

**Comment by fain182** [comment]
I think is related to https://github.com/phparkitect/arkitect/issues/329#issuecomment-1439818769

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
@fain182 How would you express the above "or" relation in class names?

**Comment by fain182** [comment]
I think there is no way to do it, I created an issue regarding this.

**Comment by szepeviktor** [comment]
@smortexa New feature added to PHPArkitect.
Could you fix this issue?

**Comment by smortexa** [comment]
Yes, I will.

**Comment by smortexa** [comment]
Fixed in latest release (v0.6.0).
