### ISSUE TITLE
Extending Model through another class produces a violation

### ISSUE THREAD

**Issue by szepeviktor** [smortexa/laravel-arkitect#23]
```
App\Models\SoftSkill has 1 violations
  should extend Illuminate\Database\Eloquent\Model because we use Laravel framework!
```
https://github.com/smortexa/laravel-arkitect/blob/main/src/Rules/Extending/ModelsExtending.php

Hello! `SoftSkill` is extending `Model` this way.

```php
abstract class Taxonomy extends Model
```
```php
class SoftSkill extends Taxonomy
```

What should I do to code correctly?

**Comment by smortexa** [comment]
You can publish the package configuration file and comment that rule and create your own custom rule for your models.
